#!/bin/bash

#
# Copy this script into the root of the Android source code and run, to build the firmware
#

export USE_CCACHE=1
export CCACHE_DIR=~/.ccache/los14.1-lt033g

if [ ! -d "$CCACHE_DIR" ]; then
    mkdir "$CCACHE_DIR"
fi

# Set ccache 50GB
./prebuilts/misc/linux-x86/ccache/ccache -M 50G

# Enable SU
export WITH_SU=true

. build/envsetup.sh

device/samsung/lt033g/patches/applypatch.sh

rm -f ~/AndroidSources/LineageOS-14.1/master/device/samsung/lt033g/patches/applypatch.sh

breakfast lt033g
brunch lt033g
